Fix string formatting error.
the {reaction:s} was causing a
TypeError: unsupported format string passed to TemplateReaction.__format__
but {reaction} should do the intended conversion.
This line is seldom hit.